name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Test Debug
        run: dotnet test -c Debug --no-restore --verbosity normal --collect:"XPlat Code Coverage"
      - name: Test Release
        run: dotnet test -c Release --no-restore --verbosity normal --collect:"XPlat Code Coverage"